### ISSUE TITLE
Horvath2 - a typo and naming consistency

### ISSUE THREAD

**Issue by JasonR055** [isglobal-brge/methylclock#10]
Hi there, 

I very much appreciate this library and have been using it across the last month or two.

A couple of things of note,

In file DNAmage.R, L253, please correct a typo:

```
change     skinHorvath <- ageAcc2(skinHorvath, df, lab = "Hovarth2")
to         skinHorvath <- ageAcc2(skinHorvath, df, lab = "Horvath2")
```
Also, consider consistent naming for this clock, either skinHorvath or Hovarth2. It's easier to build loops on returned data with consistent naming.

**Comment by dpelegri** [comment]
Hi Jason,

Thanks for your comments and suggestions. 

We have renamed Horvath2 to skynHorvath as you suggested, this makes it more understandable.

Best,
