### ISSUE TITLE
Is Hannum age correct??

### ISSUE THREAD

**Issue by tomkuipers1402** [isglobal-brge/methylclock#12]
Hi,

I'm using methylclock to calculate various clocks, including Hannum. Besides methylclock I'm also using GrimAge which also returns a Hannum age. What caught my eye is that the Hannum ages are very different (~5 year difference). I then checked another R tool (cgageR) & the web tool from Horvath to verify both Hannum results, and these returned the exact same ages as GrimAge does. So now I'm very curious to know why your calculation of Hannum is so different.

A reproducible example:
I did a test using the "dat0BloodIllumina450K" dataset from Horvaths website (https://horvath.genetics.ucla.edu/html/dnamage/). I used this set in methylclock & their own web tool (http://dnamage.genetics.ucla.edu/home) just as reference (or cgageR for that matter). Below are the output from each analysis:

| |  | Horvath | Horvath | Hannum | Hannum | Levine | Levine | skinHorvath | skinHorvath|
|--- | --- | --- | --- | --- | --- | --- | --- | --- | ---|
|SampleID | Chronological | Methylclock | website | Methylclock | website | Methylclock | website | Methylclock | website|
|Sample1 | 54 | 56.40613057 | 56.40613057 | 67.97281509 | 62.38395578 | 63.69309142 | 63.69296394 | 57.87486951 | 57.87486951|
|Sample2 | 61 | 53.3333378 | 53.3333378 | 75.85577134 | 69.3625622 | 69.65720737 | 69.65707989 | 63.52767866 | 63.52767866|
|Sample3 | 51 | 42.88095788 | 42.88095788 | 69.06511562 | 63.33772736 | 60.01958205 | 60.01945457 | 53.41694824 | 53.41694824|
|Sample4 | 49 | 49.66514624 | 49.66514624 | 65.3893445 | 60.64285613 | 59.9686585 | 59.96853102 | 54.14267335 | 54.14267335|
|Sample5 | 60 | 59.7888936 | 59.7888936 | 74.62617747 | 69.5195625 | 61.98412288 | 61.9839954 | 65.99091495 | 65.99091495|
|Sample6 | 44 | 42.39851636 | 42.39851636 | 61.5230668 | 56.62311564 | 62.29411828 | 62.2939908 | 50.89238517 | 50.89238517|
|Sample7 | 44 | 42.59163084 | 42.59163084 | 54.95363471 | 48.4001517 | 45.75172444 | 45.75159696 | 51.46764711 | 51.46764711|
|Sample8 | 44 | 44.8255743 | 44.8255743 | 63.8710032 | 58.71293305 | 60.30713587 | 60.30700839 | 52.96796253 | 52.96796253|
|Sample9 | 50 | 52.23688708 | 52.23688708 | 72.4938971 | 66.45257321 | 62.09370501 | 62.09357753 | 58.54669773 | 58.54669773|
|Sample10 | 45 | 48.47986667 | 48.47986667 | 68.24220286 | 62.11073585 | 65.64209699 | 65.64196951 | 56.10547055 | 56.10547055|
|Sample11 | 44 | 39.64655546 | 39.64655546 | 62.75810044 | 57.02140051 | 54.52849928 | 54.5283718 | 49.9444891 | 49.9444891|
|Sample12 | 56 | 66.71139069 | 66.71139069 | 83.58793981 | 78.30729348 | 72.1303907 | 72.13026322 | 66.58504288 | 66.58504288|
|Sample13 | 36 | 43.4434294 | 43.4434294 | 60.44763689 | 54.49256252 | 46.12905568 | 46.45391493 | 48.41746685 | 48.41324397|
|Sample14 | NA | 47.88172647 | 47.88172647 | 60.01940224 | 53.82554186 | 55.90011527 | 55.89998779 | 52.80662669 | 52.80662669|
|Sample15 | 36 | 35.04433888 | 35.04433888 | 54.94983951 | 49.2669058 | 46.53487967 | 46.53475219 | 41.3809557 | 41.3809557|

You can see that Horvath, Levine & Horvath2/skin are all the same, but Hannum is clearly not. Any ideas??

PS. I'm using methylclock v0.7.5 (the latest master)

Best, Tom

**Comment by isglobal-brge** [comment]
Hi Tom, I am not sure what can happen. Are the clocks estimated using all CpGs? In other works are there any missing CpGs for Hannum? (If so you will see a warning when computing the clock - also you can use the function `checkClocks()`)

**Comment by tomkuipers1402** [comment]
No, all were present. I used the same dataset in methylclock, Horvaths website, GrimAge, and cgageR. Only methylclock gave back a different age relative to the others tools. The same goes for using my own data. I also had contact with a colleague of mine who has tested this as well, and she found the same phenomenon.

**Comment by isglobal-brge** [comment]
Thanks for the feedback! Is only Hannum the different one? I mean, is Horvath providing the same answer using the other tools?

**Comment by isglobal-brge** [comment]
I guess the problem is related to the CpGs used when estimating Hannum's clock. 

For example, if you execute this:

library(methylclock)
library(cgageR)

DNAmAge(TestDataset, clocks=c("Hannum", "Horvath"))

tt <- TestDataset[,-1]
rownames(tt) <- TestDataset[,1]
getAgeR(tt, horvath = TRUE, hannum = TRUE)


methylclock returns NA since only these CpGs are found

[1] "cg04474832" "cg05442902" "cg06493994" "cg09809672" "cg19722847" "cg21296230" "cg22736354"

(less than the required 80%, min.perc argument)

Now I will try to reproduce your example and see what's going on. 

Maybe the problem is also related to the CpGs that are called "ch.2.30415474F" and "ch.13.39564907R"  which form part of Hannum's clock and they are not regular "cg" names. 

I will say somenting today evening....

**Comment by tomkuipers1402** [comment]
> Thanks for the feedback! Is only Hannum the different one? I mean, is Horvath providing the same answer using the other tools?

Yes, all other output (Horvath, Levine, etc.) are the same. It's only Hannum that's different

**Comment by tomkuipers1402** [comment]
Thanks for looking into this! Let me know if you need more information.

**Comment by isglobal-brge** [comment]
Probably it will be related either to the order of CpGs or their names. There are some CpGs that are not named "cg.....". Just checking it!

**Comment by isglobal-brge** [comment]
Tom, I found the bug. It was related to the fact that this clock is the only one not having intercept in the model prediction. I thought I adddressed this when creating the package, but I missed one line of code that now have been fixed. 

Please, install the new version and you will see that everything is OK. Also, please, talk to your colleague and explain her that this problem has been addressed. 

This is the code you can use for the toy example you showed. 

```devtools::install_github("isglobal-brge/methylclock")

library(methylclock)
library(cgageR)

dat <- read.csv("c:/tmp/dat0BloodIllumina450K.csv")
ans1 <- DNAmAge(dat, clocks=c("Hannum", "Horvath"), fastImp = TRUE)

tt <- dat[,-1]
rownames(tt) <- dat[,1]
ans2 <- getAgeR(tt, horvath = TRUE, hannum = TRUE)

cbind(methylclock = ans1$Hannum, cgageR = ans2$HannumClock.output$Hannum.Clock.Est)
```

         methylclock Hannum.Est
Sample1     62.38396   62.38396
Sample2     69.36256   69.36256
Sample3     63.33773   63.33773
Sample4     60.64286   60.64286
Sample5     69.51956   69.51956
Sample6     56.62312   56.62312
Sample7     48.40015   48.40015
Sample8     58.71293   58.71293
Sample9     66.45257   66.45257
Sample10    62.11074   62.11074
Sample11    57.02140   57.02140
Sample12    78.30729   78.30729
Sample13    54.49256   54.49256
Sample14    53.82554   53.82554
Sample15    49.26691   49.26691

**Comment by tomkuipers1402** [comment]
Yes, it works! Thanks for getting this fixed so quickly, I really appreciate the work you've done by developing and maintaining this package.
