### ISSUE TITLE
factor bug in predAge

### ISSUE THREAD

**Issue by perishky** [isglobal-brge/methylclock#13]
The predAge() function uses coefs$CpGmarker to index the methylation matrix. The indexing isn't working as expected because for some clocks coefs$CpGmarker is a factor, not a character.

**Comment by dpelegri** [comment]
Hi perishky,

We have reviewed the clocks and all `coefs$CpGmarker` are character. We have not been able to reproduce the error, are you using it with other clocks? could you send us an example ?

Thanks

**Comment by perishky** [comment]
I encountered the problem with Lee's GA clocks.

**Comment by dpelegri** [comment]
Hi perishky,

I have checked Lee's GA clock and  coefs$CpGmarker data types is "character". I have found a bug related to the parameter `min.perc` (minimum percentage of CpGs required) in this clock. On the other had, I have added a control to take into account the factor data type
