### ISSUE TITLE
Reversed description of IEAA and EEAA in the vignette?

### ISSUE THREAD

**Issue by Ning-L** [isglobal-brge/methylclock#16]
Hi,

If I understand correctly, the intrinsic changes in the methylome do not take into account the cell types, and it is what you've written in the function `ageAcc2 `
https://github.com/isglobal-brge/methylclock/blob/325c73c6f23b090cd70f864189fa9d2dc4e51751/R/internals.R#L21-L22
So I think the descriptions of IEAA and EEAA in the vignette are reversed
https://github.com/isglobal-brge/methylclock/blob/325c73c6f23b090cd70f864189fa9d2dc4e51751/vignettes/methylclock.Rmd#L36-L37

Best regards, Lijiao

**Comment by dpelegri** [comment]
Hi, thank you for using our package!

The code to get the IEAA and the EEAA is correct,  as you comment,  IEAA and EEAA descriptions are reversed in the vignette. 
We have corrected and updated the vignette. Thanks for notifying us

Best,

**Comment by Ning-L** [comment]
Thanks for your work, I'll close this issue :)
