### ISSUE TITLE
cell.count.reference argument?

### ISSUE THREAD

**Issue by BJamon** [isglobal-brge/methylclock#2]
Hello,

I am currently trying to to make cell estimates with EPIC data. 

I can't seem to find any cell.count.reference argument. There are other arguments in the meffil package for this but not cell.count.reference.

Is it possible to detail the use of this argument in the supplementary material as well?  

Thanks.

**Comment by isglobal-brge** [comment]
I am so sorry for not having answer to this issue! I do not use to look at the GitHub repository to maintain my packages. I normally receive emails from users and then I fix the issues they explain me. 

Do you still need that? If so, I can prepare it. 

Please note that now the package will be at Bioconductor and the references should be added as an ExperimentHub .... 

https://bioconductor.org/packages/devel/data/experiment/vignettes/methylclockData/inst/doc/methylcockData.html

Thanks
