### ISSUE TITLE
Discrepancy with Bioconductor version

### ISSUE THREAD

**Issue by Alanocallaghan** [isglobal-brge/methylclock#23]
The [methylclock paper](https://academic.oup.com/bioinformatics/article/37/12/1759/5909987?login=false) and the [bioc package page](https://bioconductor.org/packages/release/bioc/html/methylclock.html) both point to this repo, but the version of the package on Bioc is completely different to the version hosted here.

Is there somewhere I can browse and possibly contribute to the current Bioc version?

**Comment by dpelegri** [comment]
Hi, thank you for using methylclock package!

You can find the version of the paper in the releases section:
          [Paper 1](https://github.com/isglobal-brge/methylclock/releases/tag/v.0.0.9)
this was the current version when the paper was published

Currently, in the default branch (main) we are maintaining a version of `methylclock` with the same features as BioC but compatible with older versions of R where the `experimentHub` package cannot be installed.
The source code for the BioC version is in the master branch.

**Comment by Alanocallaghan** [comment]
Thanks! I don't really understand your github setup but this at least helps
