### ISSUE TITLE
Can't run DNAmAge, since last update.

### ISSUE THREAD

**Issue by AndreChristianes** [isglobal-brge/methylclock#24]
I tried to run the function DNAmAge to estimate methylation Age. This used to work well with beta matrix - an object with variables (CpGs) in the rows and the observations (patients) in the collums. I named this object "myNorm". But now this returns a error message: Run: Age <-DNAmAge(myNorm, clocks="Hannum") Return: "Error in data.frame(id =rownames(cpgs, imp), Hannum = hannum): arguments imply differng number of rows: 0,40. I though this error ocours on a internal object made by the funcition, so i searched these code in github but don't have sucess. Someone can help me?

https://drive.google.com/file/d/1_YL_T7F-ttxlEmP0yMZYVSWqIHxFIceE/view?usp=sharing
example dataframe

**Comment by dpelegri** [comment]
Hi Andre,

Thank you for using our package!. 

What version of methylclock are you using?, Bioconductor or github version? I don't understand why the error occurs, it seems that the code is wrong

`data.frame( id = rownames(cpgs,imp), Hannum = hannum ) `

should be  

`data.frame(id = rownames(cpgs.imp), Hannum = hannum )`

but I have looked for the error in the code and I can't found it. I have installed the package from github and tested the `DNAmAge()` function with your data and I didn't get any error

```
> age <- DNAmAge(data, clocks = c("Hannum") ,min.perc = 0.8)
> age
# A tibble: 2 × 2
  id    Hannum
  <chr>  <dbl>
1 V1      66.4
2 V2      57.7
```
Could you uninstall and reinstall the package and test it again?

Thanks,

**Comment by AndreChristianes** [comment]
i've reinstalled and the error continues. 
At least the error message are right .-.
> Age<-DNAmAge(myNorm, clocks="Hannum")
snapshotDate(): 2022-10-31
see ?methylclockData and browseVignettes('methylclockData') for documentation
loading from cache
snapshotDate(): 2022-10-31
see ?methylclockData and browseVignettes('methylclockData') for documentation
loading from cache
snapshotDate(): 2022-10-31
see ?methylclockData and browseVignettes('methylclockData') for documentation
loading from cache
snapshotDate(): 2022-10-31
see ?methylclockData and browseVignettes('methylclockData') for documentation
loading from cache
snapshotDate(): 2022-10-31
see ?methylclockData and browseVignettes('methylclockData') for documentation
loading from cache
snapshotDate(): 2022-10-31
see ?methylclockData and browseVignettes('methylclockData') for documentation
loading from cache
snapshotDate(): 2022-10-31
see ?methylclockData and browseVignettes('methylclockData') for documentation
loading from cache
snapshotDate(): 2022-10-31
see ?methylclockData and browseVignettes('methylclockData') for documentation
loading from cache
snapshotDate(): 2022-10-31
see ?methylclockData and browseVignettes('methylclockData') for documentation
loading from cache
**Error in data.frame(id = rownames(cpgs.imp), Hannum = hannum) : 
  arguments imply differing number of rows: 0, 40**

I don't know if there are a relation with this loadings
Anyway, Thank you for helping

**Comment by dpelegri** [comment]
Hello Andre,

Regarding the data format, in your case it should be one of the following options:
- A numeric matrix with the CpG probes in rownames
- A data.frame with the CpG probes in the first column and the other numerical with beta values.
- 
![data_format](https://user-images.githubusercontent.com/43083225/213133463-2d6b264d-2b2f-46af-81f7-54b3c0044501.png)

Does the format match what you are using with DNAmAge() function?

Best

**Comment by AndreChristianes** [comment]
That was a problem in R csv import. Thank you.
