### ISSUE TITLE
EPIC array v2

### ISSUE THREAD

**Issue by Pierre9344** [isglobal-brge/methylclock#33]
Hello,

Can this package be used with the latest EPIC Array (v2).

Thank you in advance for your answer.

**Comment by dpelegri** [comment]
Hello Pierre,

Thanks you for using our package!

The clocks implemented in this package were obtained for 450K and EPIC (v1) but if EPIC (v2) is used it should work using the matching CpGs between EPIC and EPIC2.

Best

**Comment by Pierre9344** [comment]
Thank you for the answer.
Just in case someone try to do the same things, I managed to convert the CpGs IDs using the liftOver function of the sesame R package.
