### ISSUE TITLE
unit of measurement for Telomere Length clock?

### ISSUE THREAD

**Issue by joonspoon** [isglobal-brge/methylclock#4]
Hi there, saludos desde California!

Thank you so much for publishing this work, it's truly excellent.

I was excited to see your recent addition of the Telomere Length clock. May I ask, what unit it is reporting? 

When I run it clock on methylation data from an Illumina EPIC, I'm getting a number between 155-167 which seems orders of magnitude away from the measurements quoted in the research paper (between 6 and 8).

June.

**Comment by isglobal-brge** [comment]
Hi, thank you very much for your interest in our work and I do apologize for not having answered to your issue!!!

I do not use GitHub to receive feedback from my packages. I just saw this by chance. I normally use to receive comments from email.  

I will review what is happening with the units during next days

Thanks

**Comment by isglobal-brge** [comment]
Hi June! 

I fixed the problem! I transformed the output of DNAmTL estimator using the "anti.trafo" function that is normally used in Horvath's clock, but this is no necessary for this estimator. You can see here the new output

> age.gse$TL
 [1] 7.354218 6.936024 6.230067 6.857547 6.893785
 [6] 5.999434 7.506502 7.297981 6.998108 6.224743
[11] 6.975869 7.040511 6.393498 7.301631 6.856864
[16] 5.900525 7.072733 6.587335 6.189317 6.219202
[21] 7.190383 6.480689 6.461260 7.367713 6.926856
[26] 6.612764 6.865493 6.364700 7.594822 ....

So, please, install the new version and you will get the proper TL estimates

Thanks for noticing this problem.

**Comment by joonspoon** [comment]
That's super news, thanks Juan!

I'll be running them sometime in the next weeks :)

**Comment by joonspoon** [comment]
Hola Juan, 

I just wanted to let you know that my testing is coming out well.

These are readings from the first batch that I ran:

Horvath | TL length
28.7      | 7.4
31.1      | 7.4
35.0      | 7.0
43.3      | 7.0
58.0      | 7.1
69.5      | 6.6
82.7      | 6.4

There's definitely an inverse correlation between TL length and DNAmAge.

Thanks so much for sharing this work.

June.

**Comment by isglobal-brge** [comment]
Excellent June! Happy to see that our package is helping you!
