### ISSUE TITLE
Running DNAmAge method call with age parameter fails

### ISSUE THREAD

**Issue by sidohaakma** [isglobal-brge/methylclock#6]
It seems that the package expects that the `age` is variable which is included in the parent environment.

When you call the method `DNAmAge` from within your own R environment and you specify age as a environment variable the methods works. 

However if you specify age in the method call like here DNAmAge(age = age, ....) it fails. 

This error occurs: `Error in eval(predvars, data, env) : object 'age' not found`

**Comment by isglobal-brge** [comment]
It was a bug in ageAcc2 function since 'data=df' was not added into the `lm()` function. So, when age variable was not created, the function couldn't find it. Now it is fixed
