### ISSUE TITLE
Error in method "full_join"

### ISSUE THREAD

**Issue by tomkuipers1402** [isglobal-brge/methylclock#8]
Hi,

I'm getting an error when using:
```R
methylclock <- DNAmAge(
  x = beta1,
  age = age2,
  clocks = "Hannum",
  fastImp = TRUE
)
```
Which produces this error:
```R
Error in UseMethod("full_join") : 
  no applicable method for 'full_join' applied to an object of class "NULL"
```
Everything is ok when doing:
```R
methylclock <- DNAmAge(
  x = beta1,
  age = age2,
  clocks = c("Horvath","Hannum"),
  fastImp = TRUE
)
```
When Horvath isn't used, the "out" object will still be NULL when it's joined by another output:
```R
out <- NULL
  if (1 %in% method) {
    out <- Horvath
  }
  if (2 %in% method) {
    out <- out %>% full_join(Hannum, by = "id")
  }
``` 
Best regards, Tom

**Comment by isglobal-brge** [comment]
Hi Tom, 

Yes, the problem is related to the fact that I try to "full_join" something with an object that is not a table - I did not considered this situation. I'll fix it during next hours. I'll let you know when finished

**Comment by tomkuipers1402** [comment]
Alright great! Thanks

**Comment by isglobal-brge** [comment]
Hi Tom, please try the new version

**Comment by tomkuipers1402** [comment]
Perfect! Thank you very much!
